config/routes.rb
TodoLists::Application.routes.draw do
  resources :roles

  devise_for :users

  resources :todo_lists do
    resources :messages do
      member do
        get 'toggle_status'
      end
    end
  end

  root to: 'todo_lists#index'
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user

    if user.role? :administrator
      can :manage, :all
    elsif user.role? :member
      can :manage, TodoList
      can :manage, Message
    else 
      can :read, :all
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :status, :todo_list_id
  belongs_to :todo_list
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :messages
  
  def messages(options={})
    Message.all({:conditions => {:todo_list_id => self.id}}.merge(options))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  before_save :setup_role
   
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end

  # Default role is "Member"
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [1]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource

  def create
    @message = Message.create!(params[:message].merge(:todo_list_id => params[:todo_list_id]))
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def toggle_status
    @todo_list = TodoList.find(params[:todo_list_id])
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes({:status => !@message.status})
        format.js
      end
    end
  end

  def destroy
    @todo_list = TodoList.find(params[:todo_list_id])
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.js
      format.json { head :ok }
    end
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  load_and_authorize_resource
  
  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_lists }
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_list = TodoList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/new
  # GET /todo_lists/new.json
  def new
    @todo_list = TodoList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/1/edit
  def edit
    @todo_list = TodoList.find(params[:id])
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(params[:todo_list])

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render json: @todo_list, status: :created, location: @todo_list }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_lists/1
  # PUT /todo_lists/1.json
  def update
    @todo_list = TodoList.find(params[:id])

    respond_to do |format|
      if @todo_list.update_attributes(params[:todo_list])
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TodoLists" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Home', todo_lists_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
                <%= render 'shared/authentication' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
             <%- flash.each do |name, msg| -%>
                 <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
             <%- end -%>
             <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Links</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">GITHUB</li>
                  <li><%= link_to 'My GitHub', 'https://github.com/ksob' %></li>
                  <li><%= link_to 'Source', 'https://github.com/ksob/todo-lists' %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <br />
        <p>&copy; Kamil Sobieraj 2012</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <% if can? :update, @todo_list %>
      <div class="task_item">
        <%= button_to "delete", [@todo_list, message], :method => :delete, :remote => true %>
      </div>
      <div class="task_item">
        <%= check_box_tag 1, 2, message.status, :onclick=>"toggle_task_status(#{@todo_list.id}, #{message.id});" %>
      </div>
  <% else %>
      <span class="task_item">
        <%= check_box_tag 1, 2, message.status, :disabled => true %>
      </span>
  <% end %>
  <%= message.content %>
</li>

app/views/messages/_messages.html.erb
<ul id="todo_list">
    <%= render :partial => "messages/message", :collection => @todo_list.messages %>
</ul>

app/views/messages/create.js.erb
<% publish_to "/messages/new" do %>
  $("#todo_list").append("<%= j render(@message) %>");
<% end %>
$("#new_message")[0].reset();

app/views/messages/destroy.js.erb
<% publish_to "/messages/new" do %>
  $("#todo_list").replaceWith( "<ul id=\"todo_list\"><%= j render(:partial => 'message', :collection => @todo_list.messages) %></ul>")
<% end %>

app/views/messages/toggle_status.js.erb
<% publish_to "/messages/new" do %>
  $("#todo_list").replaceWith( "<ul id=\"todo_list\"><%= j render(:partial => 'message', :collection => @todo_list.messages) %></ul>")
<% end %>

app/views/shared/_authentication.html.erb
<% if user_signed_in? %>
    <li>
      <%= link_to(current_user.email, edit_user_registration_path) %>
    </li>
    <li>
      <%= link_to('Logout', destroy_user_session_path, {:method=>'delete'}) %>
    </li>
	<li>
      <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
<% else %>
    <li>
      <%= link_to('Login', new_user_session_path) %>
    </li>
	<li>
      <%= link_to('Sign up', new_user_registration_path) %>
    </li>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', :rows => 5 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                todo_lists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<%- model_class = @todo_list.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_lists/index.html.erb
<%- model_class = TodoList.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= link_to todo_list.id, todo_list_path(todo_list) %></td>
        <td><%= todo_list.name %></td>
        <td><%= todo_list.description %></td>
        <td><%=l todo_list.created_at %></td>
        <td><%= link_to t('.show', :default => t("helpers.links.show")),
                        todo_list_path(todo_list), :class => 'btn btn-mini' %></td>
        <% if can? :destroy, TodoList %>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_todo_list_path(todo_list), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          todo_list_path(todo_list),
                          :method => :delete,
                          :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                          :class => 'btn btn-mini btn-danger' %>
            </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, TodoList %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_todo_list_path,
                :class => 'btn btn-primary' %>
<% end %>

app/views/todo_lists/new.html.erb
<%- model_class = @todo_list.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_lists/show.html.erb
<%- model_class = @todo_list.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @todo_list.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @todo_list.description %></dd>
</dl>

<ul id="todo_list">
  <%= render @todo_list.messages %>
</ul>

<%= subscribe_to "/messages/new" %>

<div class="form-actions">
  <% if can? :update, @todo_list %>
      <%= form_for([@todo_list, Message.new(:todo_list_id=>@todo_list.id)], remote: true) do |f| %>
          <%= f.text_field :content %>
          <%= f.submit "Add task" %>
      <% end %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_todo_list_path(@todo_list), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  todo_list_path(@todo_list),
                  :method => 'delete',
                  :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                  :class => 'btn btn-danger' %>
  <% end %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              todo_lists_path, :class => 'btn'  %>
</div>